name: d4_geo_parse
version: 1.0.1
description: Convert GeoJSON representations to strongly typed dart structures.
repository: https://github.com/SBanksX/d4_geo_parse

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  jsontool: ^1.1.2

dev_dependencies:
  lints: ^2.0.1